<script>
export default {
  name: 'unibstarters',

  data() {
    return {
      ST: {
        Akatsuki: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          'f.5B',
          'c.5B',
          'f.5C',
          'c.5C',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.7/9B',
          'j.8B',
          'j.7/9C',
          'j.8C',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '6B',
          '6C',
          'j.6C',
          'j.2C',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          'Air Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236C',
          'j.236A',
          'j.236B',
          'j.236C',
          '214A',
          '214B',
          '214C',
          'j.214A',
          'j.214B',
          'j.214C',
          '22A',
          '22B',
          '22C',
        ],

        Byakuya: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.C',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '3C',
          '3[C]',
          'j.2C',
          'j.2[C]',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          '[B+C]',
          'Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236C',
          '236X>6A',
          '236X>6B',
          '236X>6X>6A',
          '236X>6X>6B',
          '214A',
          '214B',
          '214C',
          '214X>X>A',
          '214X>X>B',
          '214X>X>C',
          '623A',
          '623B',
          '623C',
        ],

        Carmine: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.C',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '6B',
          '6BB',
          '3B',
          '6C',
          '3C',
          '3[C]',
          'j.6B',
          'j.6BB',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          'Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236C',
          'j.236A',
          'j.236B',
          'j.236C',
          '623A',
          '623B',
          '623C',
          '214A',
          '214B',
          '214C',
          '214[A]',
          '214[B]',
          '214[C]',
          '22A',
          '22B',
          '22C',
          '63214C',
        ],

        Chaos: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.C',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '5BB',
          '5CC',
          '6C',
          'j.2C',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          'Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236C',
          '623A',
          '623B',
          '623C',
          '214A',
          '214B',
          '214C',
          '22A',
          '22B',
          '22C',
        ],

        Eltnum: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '5CC',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.C',
          'j.[C]',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '6B',
          '3C',
          '3[C]',
          'j.2B',
          'j.2[B]',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          '[B+C]',
          'Air Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236C',
          '236[A]',
          '236[B]',
          '236[C]',
          '623A',
          '623B',
          '623C',
          '214A',
          '214B',
          '214C',
          '421B',
          '421C',
          '22A',
          '22B',
          'j.214A',
          'j.214B',
          'j.214C',
        ],

        Enkidu: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '5[C]',
          '2A',
          '2B',
          '2C',
          '2[C]',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.C',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '5BB',
          '5BBB',
          '5CC',
          '5CCC',
          '2CC',
          '2CCC',
          '3C',
          '3[C]',
          '4C',
          '6C',
          '6[C]',
          'j.CC',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236[B]',
          '236C',
          '236X>6A',
          '236X>6A>6A',
          '236X>6B/C',
          '236X>6B/C>6B/C',
          '623A',
          '623B',
          '623C',
          '214A',
          '214B',
          '214C',
          '22A',
          '22B',
          '22C',
          'j.236A',
          'j.236B',
          'j.236C',
        ],

        Gordeau: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.C',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '6B',
          '4B',
          '3C',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          'Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236C',
          '236X>6X',
          '236X>6X>6X',
          '623A',
          '623B',
          '623C',
          '214A',
          '214B',
          '214C',
          '22A',
          '22B',
          '22C',
          'j.236A',
          'j.236B',
          'j.236C',
          'j.214A',
          'j.214B',
          'j.214C',
        ],

        Hilda: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '5[C]',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.C',
          'j.[C]',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '3B',
          '5BB',
          '3C',
          '3CC',
          '2CC',
          '5CC',
          'j.CC',
          'j.2C',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          'B+C~A',
          'B+C~2A',
          '[B+C]',
          'Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236C',
          '623A',
          '623B',
          '623C',
          '214A',
          '214B',
          '214C',
          '421A',
          '421B',
          '421C',
          '[A]',
          '[B]',
          '[C]',
          '22A',
          '22B',
          '22C',
          '41236C',
          'j.41236C',
        ],

        Hyde: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '[5C]',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.C',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '6B',
          '3B',
          '3C',
          'j.6C',
          'j.2C',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          '[B+C]',
          'Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236C',
          '236X~236A',
          '236X~236B/C',
          '623A',
          '623B',
          '623C',
          '214A',
          '214B',
          '214C',
          '22A',
          '22B',
          '22C',
          'j.236A',
          'j.236B',
          'j.236C',
          '41236C',
        ],

        Linne: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.C',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '6B',
          '5CC',
          '5C[C]',
          '6CC',
          '6CCC',
          'j.6B',
          'j.2B',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C~X',
          'Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236C',
          '236[B]',
          'j.236A',
          'j.236B',
          'j.236C',
          '623A',
          '623B',
          '623C',
          '214A',
          '214B',
          '214C',
          '214X~A',
          '214X~B',
          '214X~C',
          '63214A',
          '63214B',
          '63214C',
          '63214[B]',
        ],

        Merkava: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '5[C]',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.C',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '5BB',
          '2CC',
          '4B',
          '6B',
          '4C',
          '3C',
          'j.2C',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          'Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          'Flight~66',
          '236A',
          '236B',
          '236C',
          '623A',
          '623B',
          '623C',
          '214A',
          '214B',
          '214C',
          '22A',
          '22B',
          '22C',
          'j.214A',
          'j.214[A]',
          'j.214B',
          'j.214[B]',
          'j.214C',
          '41236C',
        ],

        Mika: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '5[C]',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.C',
          'j.[C]',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '5BB',
          '3B',
          '3C',
          'j.AA',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          '[B+C]',
          'Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236C',
          'j.236A',
          'j.236B',
          'j.236C',
          '623A',
          '623B',
          '623C',
          '623A/B~A',
          '623A/B~B/C',
          '623A/B~623C',
          '214A',
          '214B',
          '214C',
          '360C',
        ],

        Nanase: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '5[C]',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.C',
          'j.[C]',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '3C',
          'j.BB',
          'j.2C',
          'j.2[C]',
          'j.8C',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          'Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236C',
          '236X~A',
          '236X~B',
          '214A',
          '214B',
          '214C',
          '214X~A',
          '214X~B',
          '214X~C',
          '623A',
          '623B',
          '623C',
          'j.236A',
          'j.236B',
          'j.236C',
        ],

        Orie: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.C',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '6B',
          '3B',
          '3C',
          '4C',
          'j.2C',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          'Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236[B]',
          '236C',
          '623A',
          '623B',
          '623C',
          '214A',
          '214B',
          '214C',
          '214X~A',
          '214X~B',
          'j.214A',
          'j.214B',
          'j.214C',
          '22A',
          '22B',
          '22C',
          '41236C',
        ],

        Phonon: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '5[C]',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.C',
          'j.[C]',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '5BB',
          '4B',
          '3C',
          'j.2B',
          'j.2[B]',
          'j.4B',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66[B]',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          '[B+C]',
          'Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236[A]',
          '236B',
          '236[B]',
          '236C',
          'j.236A',
          'j.236B',
          'j.236C',
          '623A',
          '623B',
          '623C',
          '214A',
          '214A~4A',
          '214B',
          '214B~4B',
          '214C',
          '22A',
          '22B',
          '22C',
        ],

        Seth: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '5[C]',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.C',
          'j.[C]',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '5CC',
          '6C',
          '3B',
          '3C',
          'j.6C',
          'j.2C',
          'j.22~6X',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          '[B+C]',
          'Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236C',
          'j.236A',
          'j.236B',
          'j.236C',
          '623A',
          '623B',
          '623C',
          '214X~A',
          '214X~B',
          '214X~C',
          '214X~8X',
          'j.214A',
          'j.214B',
          'j.214C',
          '632146A',
          '632146B',
          '632146C',
        ],

        Vatista: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.C',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '5BB',
          'j.A+B',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          '[B+C]',
          '[B+C]8',
          '2B+C',
          'j.B+C',
          'j.[B+C]',
          'Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '[4]6A',
          '[4]6B',
          '[4]6C',
          'j.[4]6A',
          'j.[4]6B',
          'j.[4]6C',
          '[2]8A',
          '[2]8B',
          '[2]8C',
          '[6]4A',
          '[6]4B',
          '[6]4C',
          'j.[6]4A',
          'j.[6]4B',
          'j.[6]4C',
          'j.[8]2A',
          'j.[8]2B',
          'j.[8]2C',
          ']X[',
          'j.]X[',
        ],

        Wagner: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '5[C]',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.C',
          'j.[C]',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '2A+D',
          '6B',
          '3C',
          '6C',
          'j.2C',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          '[B+C]',
          'Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236C',
          'j.236A',
          'j.236[A]',
          'j.236B',
          'j.236[B]',
          'j.236C',
          '623A',
          '623B',
          '623C',
          '214A',
          '214B',
          '214C',
          '214[A]',
          '214[B]',
          '214[C]',
          '22C',
        ],

        Waldstein: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '5[C]',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.C',
          'j.[C]',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '1A',
          '4B',
          '6C',
          '3C',
          'j.6C',
          'j.2C',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          'Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236C',
          '623A',
          '623B',
          '623C',
          '360A',
          '360B',
          '360C',
          '214A',
          '214B',
          '214[B]',
          '214C',
          'j.214A',
          'j.214B',
          'j.214C',
          '[4]6A',
          '[4]6B',
          '[4]6C',
        ],

        Yuzuriha: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.C',
          'j.[C]',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '6A',
          '6B',
          '6C',
          'j.6A',
          'j.6B',
          'j.6C',
          '4B',
          '4C',
          'j.2C',
          'j.2[C]',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          '[B+C]',
          'j.B+C',
          'j.[B+C]',
          'Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236C',
          'j.236A',
          'j.236B',
          'j.236C',
          '214A',
          '214B',
          '214C',
          'j.214A',
          'j.214B',
          'j.214C',
        ],
      },

      CLR: {
        Akatsuki: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          'f.5B',
          'c.5B',
          'f.5C',
          'c.5C',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.7/9B',
          'j.8B',
          'j.7/9C',
          'j.8C',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '6B',
          '6C',
          'j.6C',
          'j.[6]C',
          'j.2C',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          'Air Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236C',
          'j.236A',
          'j.236B',
          'j.236C',
          '214A',
          '214B',
          '214C',
          'j.214A',
          'j.214B',
          'j.214C',
          '22A',
          '22B',
          '22C',
        ],

        Byakuya: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.C',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '5BB',
          '3C',
          '3[C]',
          'j.2C',
          'j.2[C]',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          '[B+C]',
          'Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236C',
          '236X>6A',
          '236X>6B',
          '236X>6X>6A',
          '236X>6X>6B',
          '214A',
          '214B',
          '214C',
          '214X>X>A',
          '214X>X>B',
          '214X>X>C',
          '214[X]>A',
          '214[X]>B',
          '214[X]>C',
          '623A',
          '623B',
          '623C',
        ],

        Carmine: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.BB',
          'j.C',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '4B',
          '6B',
          '6BB',
          '3B',
          '6C',
          '3C',
          '3[C]',
          'j.6B',
          'j.6BB',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          'Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236C',
          'j.236A',
          'j.236B',
          'j.236C',
          '623A',
          '623B',
          '623C',
          '214A',
          '214B',
          '214C',
          '214[A]',
          '214[B]',
          '214[C]',
          '22A',
          '22B',
          '22C',
          '63214C',
        ],

        Chaos: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.C',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '5BB',
          '5CC',
          '6C',
          'j.2C',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          'Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236C',
          '623A',
          '623B',
          '623C',
          '214A',
          '214B',
          '214C',
          '22A',
          '22B',
          '22C',
          '[X]22~236A',
          '[X]22~236B',
          '[X]22~236C',
        ],

        Eltnum: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '5CC',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.C',
          'j.[C]',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '6B',
          '3C',
          '3[C]',
          'j.2B',
          'j.2[B]',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          '[B+C]',
          'Air Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236C',
          '236[A]',
          '236[B]',
          '236[C]',
          '623A',
          '623B',
          '623C',
          'j.623A',
          'j.623B',
          'j.623C',
          '214A',
          '214B',
          '214C',
          '421B',
          '421C',
          '22A',
          '22B',
          'j.214A',
          'j.214B',
          'j.214C',
        ],

        Enkidu: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '5[C]',
          '2A',
          '2B',
          '2C',
          '2[C]',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.C',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '5BB',
          '5BBB',
          '5CC',
          '5CCC',
          '2CC',
          '2CCC',
          '3C',
          '3[C]',
          '4C',
          '4[C]',
          '6C',
          '6[C]',
          'j.CC',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236[B]',
          '236C',
          '236X>6A',
          '236X>6A>6A',
          '236X>6B/C',
          '236X>6B/C>6B/C',
          '623A',
          '623B',
          '623C',
          '214A',
          '214B',
          '214C',
          '22A',
          '22B',
          '22[B]',
          '22C',
          'j.236A',
          'j.236B',
          'j.236C',
        ],

        Gordeau: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.C',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '6B',
          '4B',
          '3C',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          'Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236C',
          '236X>6X',
          '236X>6X>6X',
          '623A',
          '623B',
          '623C',
          '623X~6B',
          '214A',
          '214B',
          '214C',
          '22A',
          '22B',
          '22C',
          'j.236A',
          'j.236B',
          'j.236C',
          'j.214A',
          'j.214B',
          'j.214C',
        ],

        Hilda: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '5[C]',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.C',
          'j.[C]',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '3B',
          '5BB',
          '3C',
          '3CC',
          '2CC',
          '5CC',
          'j.CC',
          'j.2C',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          'B+C~A',
          'B+C~2A',
          '[B+C]',
          'Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236C',
          '623A',
          '623B',
          '623C',
          '214A',
          '214B',
          '214C',
          '421A',
          '421B',
          '421C',
          '[A]',
          '[B]',
          '[C]',
          '22A',
          '22B',
          '22C',
          '41236C',
          'j.41236C',
        ],

        Hyde: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '[5C]',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.C',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '6B',
          '3B',
          '3C',
          'j.6C',
          'j.2C',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          '[B+C]',
          'Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236C',
          '236X~236A',
          '236X~236B',
          '236X~236C',
          '623A',
          '623B',
          '623C',
          '214A',
          '214B',
          '214C',
          '22A',
          '22B',
          '22C',
          'j.236A',
          'j.236B',
          'j.236C',
          '41236C',
        ],

        Linne: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.C',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '6B',
          '5CC',
          '5C[C]',
          '6CC',
          '6CCC',
          'j.6B',
          'j.2B',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C~X',
          'Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236C',
          '236[B]',
          'j.236A',
          'j.236B',
          'j.236[B]',
          'j.236C',
          '623A',
          '623B',
          '623C',
          '214A',
          '214B',
          '214C',
          '214X~A',
          '214X~B',
          '214X~C',
          '63214A',
          '63214B',
          '63214C',
          'j.63214A',
          'j.63214B',
          'j.63214C',
          '63214[B]',
        ],

        Londrekia: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.C',
          'j.[C]',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '5BB',
          '6B',
          '4C',
          '4CC',
          '3C',
          'j.3B',
          'j.3[B]',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          'Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236[B]',
          '236C',
          '214A',
          '214B',
          '214C',
          '214[A]',
          '214[B]',
          '214[C]',
          '22A',
          '22B',
          '22C',
          '623A',
          '623B',
          '623C',
        ],

        Merkava: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '5[C]',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.C',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '5BB',
          '2CC',
          '4B',
          '6B',
          '4C',
          '3C',
          'j.2C',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          'Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          'Flight~66',
          '236A',
          '236B',
          '236[B]',
          '236C',
          '623A',
          '623B',
          '623C',
          '214A',
          '214B',
          '214C',
          '22A',
          '22B',
          '22[B]',
          '22C',
          'j.214A',
          'j.214[A]',
          'j.214B',
          'j.214[B]',
          'j.214C',
          '41236C',
        ],

        Mika: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '5[C]',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.C',
          'j.[C]',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '5BB',
          '3B',
          '3C',
          'j.AA',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          '[B+C]',
          'Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236C',
          'j.236A',
          'j.236B',
          'j.236C',
          '623A',
          '623B',
          '623C',
          'j.623A',
          'j.623B',
          'j.623C',
          '623A/B~A',
          '623A/B~B/C',
          '623A/B~623C',
          '214A',
          '214B',
          '214C',
          '360C',
        ],

        Nanase: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '5[C]',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.C',
          'j.[C]',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '3C',
          'j.BB',
          'j.2C',
          'j.2[C]',
          'j.8C',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          'Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236C',
          'j.236A',
          'j.236B',
          'j.236C',
          '236X~A',
          '236X~B',
          '214A',
          '214B',
          '214C',
          '214X~A',
          '214X~B',
          '214X~C',
          'j.214A',
          'j.214B',
          'j.214C',
          'j.214X~A',
          'j.214X~B',
          'j.214X~C',
          '623A',
          '623B',
          '623C',
        ],

        Orie: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.C',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '6B',
          '3B',
          '3C',
          '4C',
          'j.2C',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          'Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236[B]',
          '236C',
          '623A',
          '623B',
          '623C',
          '214A',
          '214B',
          '214C',
          '214X~A',
          '214X~B',
          '214X~C',
          'j.214A',
          'j.214B',
          'j.214C',
          '22A',
          '22B',
          '22C',
          '41236C',
        ],

        Phonon: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '5[C]',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.C',
          'j.[C]',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '5BB',
          '4B',
          '3C',
          'j.2B',
          'j.2[B]',
          'j.4B',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66[B]',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          '[B+C]',
          '6B+C~A',
          '6B+C~B',
          '6B+C~C',
          'Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236[A]',
          '236B',
          '236[B]',
          '236C',
          'j.236A',
          'j.236B',
          'j.236C',
          '623A',
          '623B',
          '623C',
          '214A',
          '214A~4A',
          '214B',
          '214B~4B',
          '214C',
          '22A',
          '22B',
          '22C',
          'j.22A',
          'j.22B',
          'j.22C',
        ],

        Seth: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '5[C]',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.C',
          'j.[C]',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '5CC',
          '6C',
          '3B',
          '3C',
          'j.6C',
          'j.2C',
          'j.22~6X',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          '[B+C]',
          'Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236C',
          'j.236A',
          'j.236B',
          'j.236C',
          '623A',
          '623B',
          '623C',
          'j.623A',
          'j.623B',
          'j.623C',
          '214X~A',
          '214X~B',
          '214X~C',
          '214X~8X',
          'j.214A',
          'j.214B',
          'j.214C',
          '632146A',
          '632146B',
          '632146C',
        ],

        Vatista: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.C',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '5BB',
          '2BBB',
          'j.A+B',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          'B+C~A',
          '[B+C]',
          '[B+C]~A',
          '[B+C]8',
          '2B+C',
          'j.B+C',
          'j.[B+C]',
          'Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '[4]6A',
          '[4]6B',
          '[4]6C',
          'j.[4]6A',
          'j.[4]6B',
          'j.[4]6C',
          '[2]8A',
          '[2]8B',
          '[2]8C',
          '[6]4A',
          '[6]4B',
          '[6]4C',
          'j.[6]4A',
          'j.[6]4B',
          'j.[6]4C',
          'j.[8]2A',
          'j.[8]2B',
          'j.[8]2C',
          ']X[',
          'j.]X[',
        ],

        Wagner: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '5[C]',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.[B]',
          'j.C',
          'j.[C]',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '2A+D',
          '6B',
          '3C',
          '6C',
          'j.2C',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          '[B+C]',
          'Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236C',
          'j.236A',
          'j.236[A]',
          'j.236B',
          'j.236[B]',
          'j.236C',
          '623A',
          '623B',
          '623C',
          '214A',
          '214B',
          '214C',
          '214[A]',
          '214[B]',
          '214[C]',
          '22C',
        ],

        Waldstein: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '5[C]',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.C',
          'j.[C]',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '1A',
          '4B',
          '6C',
          '3C',
          'j.6C',
          'j.2C',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          'Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236C',
          '236A4A',
          '623A',
          '623B',
          '623C',
          '360A',
          '360B',
          '360C',
          '214A',
          '214B',
          '214[B]',
          '214C',
          'j.214A',
          'j.214B',
          'j.214C',
          '[4]6A',
          '[4]6B',
          '[4]6C',
        ],

        Yuzuriha: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.C',
          'j.[C]',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '6A',
          '6B',
          '6C',
          'j.6A',
          'j.6B',
          'j.6C',
          '4B',
          '4C',
          'j.2C',
          'j.2[C]',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          '[B+C]',
          'j.B+C',
          'j.[B+C]',
          'Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236C',
          'j.236A',
          'j.236B',
          'j.236C',
          '214A',
          '214B',
          '214C',
          'j.214A',
          'j.214B',
          'j.214C',
        ],
      },
    };
  },
};
</script>
