<script>
export default {
  name: 'unibstarters',

  data() {
    return {
      ST: {
        Akatsuki: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          'f.5B',
          'c.5B',
          'f.5C',
          'c.5C',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.7/9B',
          'j.8B',
          'j.7/9C',
          'j.8C',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '6B',
          '6C',
          'j.6C',
          'j.2C',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          'Air Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236C',
          'j.236A',
          'j.236B',
          'j.236C',
          '214A',
          '214B',
          '214C',
          'j.214A',
          'j.214B',
          'j.214C',
          '22A',
          '22B',
          '22C',
        ],

        Byakuya: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.C',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '3C',
          '3[C]',
          'j.2C',
          'j.2[C]',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          '[B+C]',
          'Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236C',
          '236X>6A',
          '236X>6B',
          '236X>6X>6A',
          '236X>6X>6B',
          '214A',
          '214B',
          '214C',
          '214X>X>A',
          '214X>X>B',
          '214X>X>C',
          '623A',
          '623B',
          '623C',
        ],

        Carmine: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.C',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '6B',
          '6BB',
          '3B',
          '6C',
          '3C',
          '3[C]',
          'j.6B',
          'j.6BB',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          'Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236C',
          'j.236A',
          'j.236B',
          'j.236C',
          '623A',
          '623B',
          '623C',
          '214A',
          '214B',
          '214C',
          '214[A]',
          '214[B]',
          '214[C]',
          '22A',
          '22B',
          '22C',
          '63214C',
        ],

        Chaos: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.C',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '5BB',
          '5CC',
          '6C',
          'j.2C',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          'Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236C',
          '623A',
          '623B',
          '623C',
          '214A',
          '214B',
          '214C',
          '22A',
          '22B',
          '22C',
        ],

        Eltnum: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '5CC',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.C',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '6B',
          '3C',
          '3[C]',
          'j.2B',
          'j.2[B]',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          '[B+C]',
          'Air Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236C',
          '236[A]',
          '236[B]',
          '236[C]',
          '623A',
          '623B',
          '623C',
          '214A',
          '214B',
          '214C',
          '421B',
          '421C',
          '22A',
          '22B',
          'j.214A',
          'j.214B',
          'j.214C',
        ],

        Enkidu: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '5[C]',
          '2A',
          '2B',
          '2C',
          '2[C]',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.C',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '5BB',
          '5BBB',
          '5CC',
          '5CCC',
          '2CC',
          '2CCC',
          '3C',
          '3[C]',
          '4C',
          '6C',
          '6[C]',
          'j.CC',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236[B]',
          '236C',
          '236X>6A',
          '236X>6A>6A',
          '236X>6B/C',
          '236X>6B/C>6B/C',
          '623A',
          '623B',
          '623C',
          '214A',
          '214B',
          '214C',
          '22A',
          '22B',
          '22C',
          'j.236A',
          'j.236B',
          'j.236C',
        ],

        Gordeau: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.C',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '6B',
          '4B',
          '3C',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          'Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236C',
          '236X>6X',
          '236X>6X>6X',
          '623A',
          '623B',
          '623C',
          '214A',
          '214B',
          '214C',
          '22A',
          '22B',
          '22C',
          'j.236A',
          'j.236B',
          'j.236C',
          'j.214A',
          'j.214B',
          'j.214C',
        ],

        Hilda: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '5B',
          '5C',
          '5[C]',
          '2A',
          '2B',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.B',
          'j.C',
          'j.[C]',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '3B',
          '5BB',
          '3C',
          '3CC',
          '2CC',
          '5CC',
          'j.CC',
          'j.2C',
          { divider: true },
          { header: 'Dash Normals' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'B+C',
          'B+C~A',
          'B+C~2A',
          '[B+C]',
          'Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236C',
          '623A',
          '623B',
          '623C',
          '214A',
          '214B',
          '214C',
          '421A',
          '421B',
          '421C',
          '[A]',
          '[B]',
          '[C]',
          '22A',
          '22B',
          '22C',
          '41236C',
          'j.41236C',
        ],
      },

      CLR: {},
    };
  },
};
</script>
