<script>
export default {
  name: 'unibstarters',

  data() {
    return {
      ST: {
        Akatsuki: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '2A',
          'f.5B',
          'c.5B',
          '2B',
          'f.5C',
          'c.5C',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.7/9B',
          'j.8B',
          'j.7/9C',
          'j.8C',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '6B',
          '6C',
          'j.6C',
          'j.2C',
          { divider: true },
          { header: 'Dash Moves' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'Force Function',
          'Throw',
          'Air Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236C',
          'j.236A',
          'j.236B',
          'j.236C',
          '214A',
          '214B',
          '214C',
          'j.214A',
          'j.214B',
          'j.214C',
          '22A',
          '22B',
          '22C',
        ],

        Byakuya: [
          'All',
          { divider: true },
          { header: 'Normals' },
          { divider: true },
          '5A',
          '2A',
          'f.5B',
          'c.5B',
          '2B',
          'f.5C',
          'c.5C',
          '2C',
          { divider: true },
          { header: 'Air Normals' },
          { divider: true },
          'j.A',
          'j.7/9B',
          'j.8B',
          'j.7/9C',
          'j.8C',
          { divider: true },
          { header: 'Command Normals' },
          { divider: true },
          '6B',
          '6C',
          'j.6C',
          'j.2C',
          { divider: true },
          { header: 'Dash Moves' },
          { divider: true },
          '66B',
          '66C',
          { divider: true },
          { header: 'Universal Mechanics' },
          { divider: true },
          'Force Function',
          'Throw',
          'Air Throw',
          { divider: true },
          { header: 'Specials' },
          { divider: true },
          '236A',
          '236B',
          '236C',
          'j.236A',
          'j.236B',
          'j.236C',
          '214A',
          '214B',
          '214C',
          'j.214A',
          'j.214B',
          'j.214C',
          '22A',
          '22B',
          '22C',
        ],
      },

      CLR: {

      },
    };
  },
};
</script>
