"""empty message

Revision ID: 144adbc64468
Revises: ac4055babea4
Create Date: 2020-02-02 20:25:18.570176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '144adbc64468'
down_revision = 'ac4055babea4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('token', sa.String(length=32), nullable=True))
    op.add_column('admin', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_admin_token'), 'admin', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_token'), table_name='admin')
    op.drop_column('admin', 'token_expiration')
    op.drop_column('admin', 'token')
    # ### end Alembic commands ###
