"""empty message

Revision ID: 391793d56f62
Revises: 144adbc64468
Create Date: 2020-02-19 00:53:04.358786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '391793d56f62'
down_revision = '144adbc64468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unib_combos', sa.Column('iInstall', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_unib_combos_iInstall'), 'unib_combos', ['iInstall'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unib_combos_iInstall'), table_name='unib_combos')
    op.drop_column('unib_combos', 'iInstall')
    # ### end Alembic commands ###
