"""empty message

Revision ID: b1c7d1e6e912
Revises: 64668aa48c78
Create Date: 2020-01-31 14:48:12.061133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1c7d1e6e912'
down_revision = '64668aa48c78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unib_combos', sa.Column('flag', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unib_combos', 'flag')
    # ### end Alembic commands ###
